name: 'Upload BOM to Dependency-Track'
author: Patrick Dwyer
description: 'Uploads a CycloneDX software bill of materials to a Dependency-Track server'
inputs:
  serverUrl:
    description: 'Dependency-Track server URL (e.g. https://dependency-track.example.com:port/api/v1/bom)'
    required: true
  apikey:
    description: 'Dependency-Track API key'
    required: true
  project:
    description: 'Project in Dependency-Track'
    required: false
  projectname:
    description: 'Project name in Dependency-Track'
    required: false
  projectversion:
    description: 'Project version in Dependency-Track'
    required: false
  projecttags:
    description: 'Comma-separated list of tags (available in DT v4.12 and later)'
    default: ''
    required: false
  autocreate:
    description: "Automatically create the project in Dependency-Track if it doesn't exist"
    default: 'false'
    required: false
  isLatestProjectVersion:
    description: 'Set the project version to the latest version in Dependency-Track'
    default: 'false'
    required: false
  bomfilename:
    description: 'Path and filename of the BOM'
    default: 'bom.xml'
    required: false
  parent:
    description: 'Parent project UUID in Dependency-Track (available in DT v4.8 and later)'
    required: false
  parentname:
    description: 'Parent project name in Dependency-Track (available in DT v4.8 and later)'
    required: false
  parentversion:
    description: 'Parent project version in Dependency-Track (available in DT v4.8 and later)'
    required: false
runs:
  using: 'node20'
  main: 'index.js'
